development: &default
  # browser-sync
  basePath: './code/wp-content/themes/twentysixteen'
  server:
    port: 3000
    open: "external"
    notify: true
    reloadDebounce: 30
    proxy:
      target: 'www.creative-workflow.berlin.new.cwlocal'
      ws: true
    ui:
      port: 3001
      weinre:
        port: 3030
    ghostMode:
      clicks: true
      forms: true
      scroll: true

  # do not change unless you know why ;)
  generators:
    folder: 'ewg/generators'

  paths:
    src:
      base:       './code'
      images:     'assets/images'
      scripts:    'assets/scripts'
      styles:     'assets/styles'
      public:     'assets/public'
      views:      'views'
    dist:
      base:       './code'
      images:     'images'
      scripts:    'scripts'
      styles:     'styles'
      public:     ''
      views:      ''

  template:
    run_after_copy:
      # read the README.md for the moment you have to doit manually
      - 'npm install --cache'

test:
  <<: *default

production:
  <<: *default
