development: &default
  enabled: false
  source: ''
  target: ''
  selector: '**/*.html'
  options:
    collapseWhitespace: true
    removeComments: true
    minifyJS: true
    minifyCSS: true


test: &test
  <<: *default

production: &production
  <<: *default
